config/routes.rb
Rails.application.routes.draw do
   devise_for :admin_users, ActiveAdmin::Devise.config
   ActiveAdmin.routes(self) 
  
  root 'products#index'
   
  get "products" => "products#index" 
  
  get "products/:id" => "products#show", constraints:{id:/\d+/}, as: "product"
  
  get "products/categories/:id" => "products#category", constraints:{id:/\d+/}, as: "category"
  
  get "contentpage/:id" => "products#content_page", as: 'link' 
  get 'search_results' => 'products#search_results', as:'search_results'
  get "products/category_results/category_id" => "products#category_results",  as: "category_results"
  #get "products/category_results/Cd" => "products#category_results",  as: "category_results"
  get 'radio_results' => 'products#radio_results', as:'radio_results'
 
  post 'favourite_product/:id' =>'products#save_fav_product', as: 'save_fav_product'
  get 'forget_me_bro' =>'products#forget_me_bro', as: 'forget'
  get 'add_to_cart/:id' =>'products#add_to_cart', as: 'add_to_cart'  
  get 'remove_from_cart/:id' =>'products#remove_from_cart', as: 'remove_from_cart'
 
  get 'customer/create_customer' => 'customer#index', as: 'cust_checkout'
   get 'customer/anything' => 'customer#create_customer', as: 'something'
  #get 'customer/create' => 'customer#create', as: 'create'vreate_custome
  get 'customer/preview' => 'customer#preview', as:'preview'
  post 'customer/check_form' => 'customer#preview', as: 'create_customer'
  post 'customer/qty' => 'customer#qty', as: 'qty'
 #get 'order/create_order' =>'order#create', as: 'create_order'
#post 'order/post_order' =>'order#preview', as:'preview'
 # get 'customer/orders' => 'order#create_order', as: 'order'
  #get 'customer/create' => 'customer#create_customer', as: 'customer'
 
  #post 'customer/create_customer' => 'customer#create_customer', as: 'new_customer'
 # post 'order/create_order' => 'order#create_order', as: 'create_order'
  #get 'products/create_line_item' => 'products#create_line_item', as: 'create_line_item' 

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
end

app/models/content_page.rb
class ContentPage < ActiveRecord::Base
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :province
  has_many :orders

  def to_s
    "#{first_name} #{last_name}"
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :customer
  has_many :line_items
  has_many :products, through: :line_items
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  has_many :line_items
  has_many :orders, through: :line_items
  validates :name, presence: true, uniqueness: true
  mount_uploader :image, ProductUploader

  scope :status, -> (status) { where status: status }
end

app/models/province.rb
class Province < ActiveRecord::Base
  has_many :customers
  validates :name,  presence: true
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  before_action :initialize_products
  before_action :initialize_links

  private
def index
 if params[:category_id]
  #@category=  Category.find(params[:category_id])
  @products = Category.find(params[:category_id])
 
 end
end


  def category_params
    params.require(:category).permit(:name, :category_id)
  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  before_action :initialize_products
  before_action :initialize_links

  def order_params
    params.require(:order).permit(
      :status, :pst_rate, :gst_rate,
      :hst_rate, customer_id
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/finder_helper.rb
module FinderHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/province_helper.rb
module ProvinceHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Product List</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <script type="text/javascript" src="https://js.stripe.com/v2/"></script>

    <script type="text/javascript">
  // This identifies your website in the createToken call below
 // Stripe.setPublishableKey('pk_test_Q8lljxokI1cQ5FZ3MKGoYPK5');
 //  var stripeResponseHandler = function(status, response) {
   //   var $form = $('#payment-form');
   //   if (response.error) {
        // Show the errors on the form
    //    $form.find('.payment-errors').text(response.error.message);
    //    $form.find('button').prop('disabled', false);
    //  } else {
        // token contains id, last4, and card type
    //    var token = response.id;
        // Insert the token into the form so it gets submitted to the server
     //   $form.append($('<input type="hidden" name="stripeToken" />').val(token));
        // and re-submit
       // $form.get(0).submit();
   //   }
 //   };
  //  jQuery(function($) {
      
    //    $('#payment-form').submit(function(e) {
    //      var $form = $(this);
  
          // Disable the submit button to prevent repeated clicks
      //    $form.find('button').prop('disabled', true);
  
       //   Stripe.card.createToken($form, stripeResponseHandler);
  
          // Prevent the form from submitting with the default action
      //    return false;
     //   });
      
  //  });
    
  </script>
</head>

<body>
    <div class = 'container-fluid'>
  
        <div  class = 'row'>
           <div class = 'col-lg-12'>
             <%= render 'shared/store_header' %>
           </div>
        </div>
  
        <div class="row">  
            <div class='col-lg-2  col-md-3 col-sm-3 col-xs-12'>
             <%= render 'shared/search_aside' %>              
            </div>
              <div class='col-lg-10 col-md-9 col-sm-9 col-xs-12'>
                  <%= yield%>
            </div>
       </div>
        
        
      
  
        </div>
  
        <div  class = 'row'>
           <div class = 'col-lg-12 col-md-12'>
             <%= render 'shared/store_footer' %>
           </div>
        </div>
        
  
</body>
</html>

app/views/shared/_search_aside.html.erb
<nav class = "navbar navbar-inverse ">
            <div class = "container-fluid>"
                 <!--logo-->
                 <div class = "navbar-header">
                
                  <button type =  "button" class = "navbar-toggle" data-toggle = "collapse" data-target = ".sideNavBar">
                    <span class = "icon-bar"></span>
                     <span class = "icon-bar"></span>
                      <span class = "icon-bar"></span>
                  </button>
                
                    <a href = "#" class = "navbar-brand"> Search</a>
                  
                 </div>                
             
                 <div class = "collapse navbar-collapse sideNavBar">
                
                 <%= form_tag search_results_path, method: :get do %>
                  
                     <h1>Keyword</h1>
                  
                      <%= text_field_tag :search_keywords %>
                    <%=submit_tag 'Search' %>
                   <%end%>
                   
                       <%= form_tag category_results_path, method: :get do %>
                   
                     <h1>Category</h1>        
                 
                        <!-- <%= select_tag(:category_id, options_for_select([['All',-1],['Soaps', 5], ['Skin Care', 2],
                                              ['Shaving Care', 7],['Accessories', 6],['Bath Products', 4],
                                              ['Hair Care', 3]])) %>-->
                    
                    <%= select_tag "category_id", options_from_collection_for_select(Category.all, "id", "name"), :include_blank => true%>
                      <!-- <% @pages.each do |page| %>
                                     <li ><%= link_to page.name, category_path(page) %></li>                      
                                <% end %> -->
                       <%=submit_tag 'Search' %>
                   <%end%>
               
                <h1>Filter </h1>

                  <%= form_tag radio_results_path, method: :get do %>
                      <%= radio_button_tag('status', "New" ) %>
                      <%= label_tag("status_New", "New") %>
                      <%= radio_button_tag('status', "On Sale") %>
                      <%= label_tag( "status_On_Sale","On Sale") %>
                      
                     <div>  <%= submit_tag 'Find' %></div>                    
                       
                 <%end%>
                 
              </div>              
        
         </div>         
         
      </nav>

app/views/shared/_store_footer.html.erb
<footer>
    <div class="navigation">
      <nav role='navigation'>
        <ul class = ' nav nav-tabs' >

           <li><%= link_to 'Home', root_path %></li>
           <li><%=link_to 'Admin', admin_root_path %></li>

            <% @pages.each do |page| %>
                 <li><%= link_to page.name, category_path(page) %></li>
            <% end %>

             <% @links.each do |page| %>
                 <li><%= link_to page.title, link_path(page) %></li>
              <% end %>

          </ul>
       </nav>
    </div>
</footer>



app/views/shared/_store_header.html.erb
  
      <!--<h1 class = 'storeTitle'> Bath & Company</h1>  -->
       <!--<div class="navigation">  -->
          <nav class = "navbar navbar-inverse ">
            <div class = "container-fluid>"
                 <!--logo-->
                 <div class = "navbar-header ">
                
                  <button type =  "button" class = "navbar-toggle" data-toggle = "collapse" data-target = ".mainNavBar">
                    <span class = "icon-bar"></span>
                     <span class = "icon-bar"></span>
                      <span class = "icon-bar"></span>
                  </button>
                
                    <a href = "#" class = "navbar-brand"> Bath & Company</a>
                     <!--<div><a href = "#" class = "btn btn-sucess" id = "menu-toggle">Toggle Menu </a></div>-->
                 </div>
                 
              <div class = "collapse navbar-collapse mainNavBar">
                  <ul  class = "nav navbar-nav">
                        <li><%= link_to 'Home', root_path %></li>
                        <li><%= link_to 'Admin', admin_root_path %></li>
                            <% @links.each do |page| %>
                                     <li><%= link_to page.title, link_path(page) %></li>                     
                             <% end %>     
                        
                        <li class = "dropdown">
                          <a href = "#" class = "dropdown-toggle" data-toggle = "dropdown">Categories <span class = "caret"</span></a>
                          <ul class = "dropdown-menu">                             
                                <% @pages.each do |page| %>
                                     <li ><%= link_to page.name, category_path(page) %></li>                      
                                <% end %>             
                          </ul>
                        </li>
                    </ul>
                  <!-- right align-->
                  
                  
                <ul class = "nav navbar-nav navbar-right">
                    <li><a href = "#" >Log In</a></li>
                  </ul>
              </div>
         </div>
      </nav>
     
  

 