config/routes.rb
Rails.application.routes.draw do
   devise_for :admin_users, ActiveAdmin::Devise.config
   ActiveAdmin.routes(self) 
  
  root 'products#index'
   
  get "products" => "products#index" 
  
  get "products/:id" => "products#show", constraints:{id:/\d+/}, as: "product"
  
  get "products/categories/:id" => "products#category", constraints:{id:/\d+/}, as: "category"
  
  get "contentpage/:id" => "products#content_page", as: 'link' 
  get 'search_results' => 'products#search_results', as:'search_results'
  get "products/category_results/category_id" => "products#category_results",  as: "category_results"
  #get "products/category_results/Cd" => "products#category_results",  as: "category_results"
  get 'radio_results' => 'products#radio_results', as:'radio_results'
 
  post 'favourite_product/:id' =>'products#save_fav_product', as: 'save_fav_product'
  get 'forget_me_bro' =>'products#forget_me_bro', as: 'forget'
  get 'add_to_cart/:id' =>'products#add_to_cart', as: 'add_to_cart'  
  get 'remove_from_cart/:id' =>'products#remove_from_cart', as: 'remove_from_cart'
 
  get 'customer/create_customer' => 'customer#index', as: 'cust_checkout'
   get 'customer/anything' => 'customer#create_customer', as: 'something'
  #get 'customer/create' => 'customer#create', as: 'create'vreate_custome
  get 'customer/preview' => 'customer#preview', as:'preview'
  post 'customer/check_form' => 'customer#preview', as: 'create_customer'
  post 'customer/qty' => 'customer#qty', as: 'qty'
 #get 'order/create_order' =>'order#create', as: 'create_order'
#post 'order/post_order' =>'order#preview', as:'preview'
 # get 'customer/orders' => 'order#create_order', as: 'order'
  #get 'customer/create' => 'customer#create_customer', as: 'customer'
 
  #post 'customer/create_customer' => 'customer#create_customer', as: 'new_customer'
 # post 'order/create_order' => 'order#create_order', as: 'create_order'
  #get 'products/create_line_item' => 'products#create_line_item', as: 'create_line_item' 

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  has_many :line_items
  has_many :orders, through: :line_items
  validates :name, presence: true, uniqueness: true
  mount_uploader :image, ProductUploader

  scope :status, -> (status) { where status: status }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :initialize_products
  before_action :initialize_links

  def index
    @products = Product.all.order('name DESC').page(params[:page]).per(6)
    @new = Product.status('New').order('name')
   
      #@category = Category.find(params[:category_id])
       @categories = Category.all 
  end

  def show
    @product = Product.find(params[:id])
  end

  def content_page
    @page = ContentPage.find(params[:id])
  end


  def category
    @products = Category.find(params[:id]).products
  end



  def category_results
  
    #@products = Category.find(params[:id]).products
    #@products =Category.find(params[:category_id])
    
     #@products = Product.find(params:[category_id])
   @products = Category.find(params[:category_id]).products
    #@products = Product.all
     #@products =  Category.friendly.find(params[:id])
   # @products =Product.where (category_id: category_id) if category_id.present?
     #@category = Category.find(params[:category_id])
     
     
      #@products = Product.category_id(params[:category_id])
  end

  def search_results
    
   wildcard_keywords = '%' + params[:search_keywords] + '%'
   #where_category = ' AND category_id = ' + params[:category_id]
   
    @products = Product.where('name LIKE ? OR description LIKE ? ', wildcard_keywords,
                              wildcard_keywords)
 #  @products =  Product.where(category_id: @category)
 #@products =Product.where (category_id: category_id) if category_id.present?
   
  end

  def radio_results
    @products = Product.status(params[:status])
  end

  def create_line_item
    @line_item = LineItem.create
    line_item.product = product.id
    line_item.quantity = params[:quantity]
    line_item.price = product.price
  end

  def save_fav_product
    session[:favourite_product_id] = params[:id]
    redirect_to :back
  end

  def forget_me_bro
    session[:visit_count] = nil
    session[:products] = nil
    session[:customer_id] = nil
    redirect_to :back
  end

  def add_to_cart
    id = params[:id].to_i
    session[:products] ||= []
    session[:products] << id

    redirect_to :back
  end

  def remove_from_cart
    id = params[:id].to_i
    session[:products].delete(id)
    redirect_to :back
  end

  private

  def product_params
    params.require(:product).permit(:name, :price,
                                    :description, :image, stock_quantity,
                                    :category_id, :status)
  end

  def line_item_params
    params.require(:line_item).permit(:quantity)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_my_products.html.erb
<!--<aside id = "my_products">

 <h3>My Products</h3>

 <% if session[:products].empty? %>
  
      <p>No items in your cart</p>
    
    <% else %>
     
      <%@count= @cart_products.size%>
       <h1>Added to cart: <small><%= pluralize(@count, 'item' )%></small></h1>
       
      <ul>
        <% @cart_products.each do |product| %>
          <li>
            <%= product.name %> <%= render :partial =>'shopping', :locals => {:product => product} %>        
          </li>
    
       <% end  %>
         </ul>
  <%end%>
    
   <p><%= link_to "Continue Shopping", products_path %></p>
   <p><%= link_to "Checkout", cust_checkout_path %></p>
   
</aside>
 
-->

app/views/products/_product.html.erb

    <div class = "product">
     
        <h2><%= link_to product.name, product%></h2>
        
        <% if product.image.present? %>      
          <div class="product-image"><%=link_to (image_tag product.image.large.url), product%></div>     
        <% end %>
        
        <% if product.description.present? %>    
          <p class='description'><%= product.description%></p>
        <% end %> 
      
        <% if product.price.present? %>
           <p class = 'price'><%= number_to_currency product.price%></p>  
        <% end %> 
      
        <p><%= link_to 'Set as favourite product', save_fav_product_path(product),
                     method: :post%></p>
       
      <p><%= render :partial =>'shopping', :locals => {:product => product} %></p>
       
        <% if session[:favourite_product_id].to_i == product.id %>
                 <!--<p>This is your favourite product</p>-->
        <% end %>
   
  
</div>


app/views/products/category.html.erb
<div  class = 'row'  >
   <div class = 'col-lg-10'>
     <%= render @products %>
    </div>
</div>

app/views/products/category_results.html.erb
 
  
  <h3> Products under this category are... </h3>
   <h1> Search Results for <%= params[ :category_id] %></h1>
   <%= render @products %>



 



 

app/views/products/content_page.html.erb
<h3><%= @page.title %></h3>
<p><%= @page.content %></p>
<p>Currently under construction</p>

app/views/products/create_order.html.erb
<div>
<p>Thank you for order</p>
<p><%=@line_item%></p>

</div>

app/views/products/index.html.erb
<%= render @products %>
<%= paginate @products %>

 

app/views/products/radio_results.html.erb
<h1> Search Results for <%= params[ :status] %></h1>
 <p><%= pluralize(@products.size, 'product') %> found</p>
 <%= render @products %>


 

app/views/products/search_category.html.erb
<h1> Search Results for <%= params[ :search_keywords] %></h1>
 
<% if @products.size.zero? %>
  <p>No products found</p>
<%else%>
   <p><%= pluralize(@products.size, 'product') %> found</p>
 <%= render @products %>
 <%end%>

app/views/products/search_results.html.erb
 <h1> Search Results for <%= params[ :search_keywords] %></h1>
 
 <% if params[ :search_keywords].empty? %>
      <p>No Keywords</p>
    <%else%>
    <% if @products.size.zero? %>
      <p>No products found</p>
      <%else%>
        <p><%= pluralize(@products.size, 'product') %> found</p>
        <%= render @products %>
     <%end%>
  <%end%>
  
  <h3> Products under this category are... </h3>
  
 



 



 

app/views/products/show.html.erb
 <div  class = 'row'  >
    <div class = 'col-lg-10'>
        <%= render @product %>
    </div>
</div>