config/routes.rb
Rails.application.routes.draw do
   devise_for :admin_users, ActiveAdmin::Devise.config
   ActiveAdmin.routes(self) 
  
  root 'products#index'
   
  get "products" => "products#index" 
  
  get "products/:id" => "products#show", constraints:{id:/\d+/}, as: "product"
  
  get "products/categories/:id" => "products#category", constraints:{id:/\d+/}, as: "category"
  
  get "contentpage/:id" => "products#content_page", as: 'link' 
  get 'search_results' => 'products#search_results', as:'search_results'
  get "products/category_results/category_id" => "products#category_results",  as: "category_results"
  #get "products/category_results/Cd" => "products#category_results",  as: "category_results"
  get 'radio_results' => 'products#radio_results', as:'radio_results'
 
  post 'favourite_product/:id' =>'products#save_fav_product', as: 'save_fav_product'
  get 'forget_me_bro' =>'products#forget_me_bro', as: 'forget'
  get 'add_to_cart/:id' =>'products#add_to_cart', as: 'add_to_cart'  
  get 'remove_from_cart/:id' =>'products#remove_from_cart', as: 'remove_from_cart'
 
  get 'customer/create_customer' => 'customer#index', as: 'cust_checkout'
   get 'customer/anything' => 'customer#create_customer', as: 'something'
  #get 'customer/create' => 'customer#create', as: 'create'vreate_custome
  get 'customer/preview' => 'customer#preview', as:'preview'
  post 'customer/check_form' => 'customer#preview', as: 'create_customer'
  post 'customer/qty' => 'customer#qty', as: 'qty'
 #get 'order/create_order' =>'order#create', as: 'create_order'
#post 'order/post_order' =>'order#preview', as:'preview'
 # get 'customer/orders' => 'order#create_order', as: 'order'
  #get 'customer/create' => 'customer#create_customer', as: 'customer'
 
  #post 'customer/create_customer' => 'customer#create_customer', as: 'new_customer'
 # post 'order/create_order' => 'order#create_order', as: 'create_order'
  #get 'products/create_line_item' => 'products#create_line_item', as: 'create_line_item' 

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :province
  has_many :orders

  def to_s
    "#{first_name} #{last_name}"
  end
end

app/controllers/customer_controller.rb
class CustomerController < ApplicationController
  before_action :initialize_products
  before_action :initialize_links

  def index
    @provinces = Province.all
    render 'create_customer'
    #flash[:notice] = 'Thanks for being here!'
  end

  def create_customer
    @provinces = Province.all
    @customer = Customer.find_by(email_address: params[:email_address])

    if @customer.nil?
      @customer = Customer.create(customer_params)
      flash[:notice] = 'Thanks for Registering!'
    else
      flash[:notice] = 'Welcome back!'
    end
    session[:customer_id] = @customer.id
  end

  def preview
    create_customer
    @customer = Customer.find(session[:customer_id])
    @province = Province.find(@customer.province_id)
  end

  def qty
    @customer = Customer.find(session[:customer_id])
    @province = Province.find(@customer.province_id)
    @order = create_order
    @line_items = []

    @cart_products.each do |product|
    @line_items << create_line_item(product)
    end
  end

  def create_line_item(product)
    line_item_args =
      {
        'quantity' => params[:quantity],
        'price' => product.price,
        'product_id' => product.id,
        'order_id' => @order.id
      }
    LineItem.create(line_item_args)
  end

  def create_order
    order_data =
    {
      'status' => 'pending',
      'pst_rate' => @province.pst,
      'gst_rate' => @province.gst,
      'hst_rate' => @province.hst,
      'customer_id' => @customer.id
    }
    Order.create(order_data)
  end

  def customer_params
    {
      'first_name' => params.require(:first_name),
      'last_name' => params.require(:last_name),
      'email_address' => params.require(:email_address),
      'province_id' => params.require(:province_id),
      'address' => params.require(:address),
      'city' => params.require(:city)
    }
  end
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/views/customer/_final.html.erb
<aside id = "my_invoice">

<h3>Final Order</h3>

<% if session[:products].empty? %>

    <p>No invoice at this time</p>
    
    <% else %>

    <%@count= @cart_products.size
    @tax= 0
    @subtotal=0
    @total_pst =0
    @total_gst =0
    @total_hst =0
    @grand_total = @subtotal + @tax=%>
 
     <h1>Invoice for: <%= @customer.first_name %></h1>
 
     <%#<form method="post" class="form-horizontal" action="/products/create_order" role="form" > %>
 
      <ul>
        <% @cart_products.each do |product| %>
        <% qty = params['quantity' + product.id.to_s].to_i %>
      
         <%#@tax_total = product.price * @tax%>
          <%#@product_with_tax= product.price + @tax_total%>

             
          <li>
            <p>product name<%= product.name %></p>
            <p>product description<%= product.description %></p>
            <p>product price<%=number_to_currency( product.price) %> x <%= qty %></p>
               
              <%@subtotal+=(product.price*qty)%>          

          </li>
              
        <% end  %>
      </ul>
      
        <% if @province.gst.present?%>
           <%@tax+=@subtotal*@province.gst.round(2) %>
           <%  @total_gst+=@subtotal* @province.gst.round(2) %>   
        <% end%>
    
         <% if @province.pst.present?%>
             <%@tax+= @subtotal* @province.pst.round(2)  %>
                <%  @total_pst+=@subtotal* @province.pst.round(2) %>   
         <% end%>
         
         <% if @province.hst.present?%>
              <%@tax+= @subtotal* @province.hst.round(2) %>
                 <%  @total_hst+=@subtotal* @province.hst.round(2) %>   
         <% end%>
         
 <div>
    </br> </br> </br>
     <p>Total of products <%=number_to_currency(@subtotal)%></p>
     
     
      <%if @province.pst.present?%>
        <p>Total pst <%= number_to_currency(@total_pst)%></p>
      <%end%>
      
         <%if @province.gst.present?%>
                <p>Total gst <%=number_to_currency(@total_gst)%></p>
         <%end%>
        
         <%if @province.hst.present?%>
            <p>Total hst <%= number_to_currency(@total_hst)%></p>
         <%end%>
         
        <p> Grand Total: <%=number_to_currency(@tax + @subtotal)%></p>
</div>
<% end %>
</aside>

app/views/customer/_my_invoice.html.erb
<div class = 'row'>
<div class = 'col-lg 8'>
<aside id = "my_invoice">

<h2>Please choose your quantity</h2>

<% if session[:products].empty? %>

    <p>No invoice at this time</p>
    
    <% else %>
        
    <%@count= @cart_products.size
    @tax= 0
    @subtotal=0
    @total_pst =0
    @total_gst =0
    @total_hst =0%>
 
     <h3>Invoice for: <%= @customer.first_name %></h3>
    <% if flash[:notice] %>
        <div class="notice"><%= flash[:notice] %></div>
    <% end %>   
 
     <%#<form method="post" class="form-horizontal" action="/products/create_order" role="form" > %>
     <%= form_tag({controller: "customer", action:"qty"},method: "post") %>

      <ul>
        <% @cart_products.each do |product| %>
        <div class ='row'>
        
             <li> product name:<%= product.name %>  </li>
             <li> product description:<%= product.description %></li>
             <li> product price:<%=number_to_currency( product.price) %></li>
        </div> 
           
            <div class = 'row'
            <div class="form-group">
              <%= field_name = ('quantity'+ product.id.to_s)
                      label_tag field_name, nil, class: "col-sm-2 control-label" %>
                      
                     
              <div class="col-sm-4">
                <%= text_field_tag field_name, nil, class: "form-control" %>
              </div>
            </div>
      
        
           
        <% end  %>
      </ul>
      
       
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= submit_tag 'Submit', class: 'btn btn-success' %>        
    </div>
  </div>
<% end %>

</aside>
  </div>
</div>


app/views/customer/_my_products.html.erb
<aside id = "my_products">

 <h3>My Products</h3>

 <% if session[:products].empty? %>
  
      <p>No items in your cart</p>
    
    <% else %>
     
      <%@count= @cart_products.size%>
       <h1>Added to cart: <small><%= pluralize(@count, 'item' )%></small></h1>
       
      <ul>
        <% @cart_products.each do |product| %>
          <li>
            <%= product.name %> <%= render :partial =>'shopping', :locals => {:product => product} %>        
          </li>
    
       <% end  %>
         </ul>
  <%end%>
    
   <p><%= link_to "Continue Shopping", products_path %></p>
   <p><%= link_to "Checkout", create_customer_path %></p>
   
</aside>
 

app/views/customer/_shopping.html.erb
<% if session[:products].include?(product.id) %>
  <%= link_to 'Remove from cart', remove_from_cart_path(product) %>
  <%else%>

 <%= link_to 'Add to cart', add_to_cart_path(product) %>
 <%end%>
 

app/views/customer/create_customer.html.erb
<div class = 'row'>
  <div class ='col-xs-10 col-md-8 col-lg-12'>

<%= form_tag create_customer_path, method: :post, :class => "form-horizontal", :role => 'form' do %>
 
  <div class="form-group">
    <%= label_tag :first_name, nil, class: "col-sm-2  control-label" %>
    <div class="col-sm-6 col-md-12 col-lg-6">
      <%= text_field_tag :first_name, nil, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= label_tag :last_name, nil, class: "col-sm-2  control-label" %>
    <div class="col-sm-6 col-md-12 col-lg-6 ">
      <%=  text_field_tag :last_name, nil, class: "col-sm-2 form-control" %>
    </div>
  </div>
    <div class="form-group">
    <%= label_tag :email_address, nil, class: "col-sm-2  control-label" %>
    <div class="col-sm-6 col-md-12 col-lg-6">
      <%=  text_field_tag :email_address, nil, class: "col-sm-2 form-control" %>
    </div>
  </div>
    <div class="form-group">
    <%= label_tag :address, nil, class: "col-sm-2  control-label" %>
    <div class="col-sm-6 col-md-12 col-lg-6">
      <%=  text_field_tag :address, nil, class: "col-sm-2 form-control" %>
    </div>
  </div>
     <div class="form-group">
    <%= label_tag :city, nil, class: "col-sm-2  control-label" %>
    <div class="col-sm-6 col-md-12 col-lg-6 ">
      <%=  text_field_tag :city, nil, class: "col-sm-2 form-control" %>
    </div>
  </div>
     <div class="form-group">
    <%= label_tag :province_id, nil, class: "col-sm-2  control-label" %>
    <div class="col-sm-6 col-md-12 col-lg-6">     
     <%= select_tag :province_id, options_from_collection_for_select(@provinces, 'id', 'name') , class: "col-sm-2 form-control"%>

    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-4 col-sm-10">
      <%= submit_tag 'Submit', class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

  </div>
</div>

app/views/customer/get_qty.html.erb
<p><%= render 'final'%></p>

app/views/customer/preview.html.erb
<div>


<%= render 'my_invoice' %>
 
</div>
<div>
 
</div>

app/views/customer/qty.html.erb
<p><%= render 'final'%></p>